name: test_action
on:
  push:
    branches:
      - dev

jobs:
  Test-Docker:
    runs-on: ubuntu-latest
    steps:
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: Check out the repo
       uses: actions/checkout@v2
       with:
         submodules: recursive
     - name: Login to DokerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_HUB_NAME }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}

