name: test_action
on:
  push:
    branches:
      - dev

jobs:
  Test-Docker:
    runs-on: ubuntu-latest
    steps:
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: Check out the repo
       uses: actions/checkout@v2
       with:
         submodules: recursive
     - name: Login to DokerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_HUB_NAME }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
     - name: Build and push Docker image
       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
       with:
         context: .
         push: true
         tags: qiyuncui/testdocker:latest
     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SE_SSH_PRIVATE_KEY }}
         known_hosts: unnecessary
     - name: add known_hosts
       run: ssh-keyscan -p 22 -H ${{ secrets.SE_SSH_IP }}  >> ~/.ssh/known_hosts
     - name: run docker compose in server
       run: docker compose -H ${{ secrets.SSH_DSN }} up 

